### ISSUE TITLE
Bug: CLI tool doesn't respect pinned AstroCommunity version

### ISSUE THREAD

**Issue by mehalter** [Uzaaft/astrocommunity-cli#4]
If a user pins their AstroCommunity clone to a specific version either tracking stable releases or even a specific commit, the CLI tool always shows the current unstable release of AstroCommunity. This should respect the settings that the user has for their clone of AstroCommunity and only show plugins that they actually can add.

**Comment by Uzaaft** [comment]
Notes from discord convo:
This should see which branch/tag it's currently checked out, and then fetch the tree from that

**Comment by Uzaaft** [comment]
@mehalter I think we should just as a matter of rule always fetch the current commit that's in the user's lazy folder, unless it's not there. What do you think?

**Comment by mehalter** [comment]
Why do a separate clone as well, why not just use the users lazy folder as the place you are searching

**Comment by Uzaaft** [comment]
Yeah that's what I said. We use the users lazy folder, if astrocom is not there we'll use the current HEAD

**Comment by Uzaaft** [comment]
Either use the current commit in the git repo, or just use the current lazy-lock.json file

**Comment by mehalter** [comment]
Ah I just meant, are you doing your own clone of the AstroCommunity repo separately? Or just using the folder in the users lazy directory entirely?

**Comment by Uzaaft** [comment]
Planning to use the folder in the users lazy dir. There's no clones at the CLI's end

**Comment by Uzaaft** [comment]
convo @ discord summed up: Use the local folder

**Comment by Uzaaft** [comment]
I'm gonna split the thought about this in two issues:

- [x] Respecting the user's commit in their lazy-lock.json file, but no offline mode
- [x] Making offline mode default with fallback to online of repository is not found.

**Comment by Uzaaft** [comment]
Part 1 was implemented with de3d941ec2f4b6cad2810f767cbfa2e67158e9be...0e40ed43ec13203de715a88fefbcd006c89d3eda

**Comment by Uzaaft** [comment]
Offline mode as default implemented.
